### PR TITLE
Electron-231 (Fixes the installer config issue on Windows)

### PR DESCRIPTION
**Pull request by KiranNiranjan**
## Description
Fixed the regex in .aip to write the correct value to the user config  [JIRA-ticket](https://perzoinc.atlassian.net/browse/ELECTRON-231)

## Approach
How does this change address the problem?
- #### Problem with the code: Regex was looking for the `"minimizeOnClose";\s*:\s*false` instead of the value true
- #### Fix: Changed the regex to `"minimizeOnClose";\s*:\s*true`

@VikasShashidhar & @VishwasShashidhar Please review. Thanks

### CODE REVIEW

**Comment by VishwasShashidhar** [comment]
lgtm 👍

So, basically because the default value was changed, we needed to update the regex right?

**Comment by KiranNiranjan** [comment]
@VishwasShashidhar Yep :)

**Comment by VikasShashidhar** [comment]
The JIRA ticket says that this issue happens for "Always on Top" as well. Should we not address that too?

**Comment by VishwasShashidhar** [comment]
That's true. @KiranNiranjan Please do the needful.

**Comment by KiranNiranjan** [comment]
@VikasShashidhar & @VishwasShashidhar The issue was only with the ```Minimize on Close```.

```Always on Top``` and ```Launch on Startup``` are working as expected.

**Pull request merged**
