### PR TITLE
fix: SDA-2465 Clamping the display id to ensure we are not accessing outside the array

### PR DESCRIPTION
**Pull request by mattias-symphony**
## Description
A few sentences describing the overall goals of the pull request's commits. 
Describe the problem or feature in addition to a link to the 
[SDA-2465](https://perzoinc.atlassian.net/browse/SDA-2465)

## Solution Approach
To ensure we are not reading outside of the array, we clamp the value to not be outside of valid indices for the array.

## Related PRs
List related PRs against other branches/repositories:

branch | PR
------ | ------
other_pr_dev | [link]()

### CODE REVIEW

**Review by psjostrom — APPROVED** [review]

**Comment by VishwasShashidhar** [comment]
@mattias-symphony Please describe the solution in the description. It'll help in the future if someone looks at the code to understand what clamping does exactly.

**Review by johankwarnmarksymphony — APPROVED** [review]

**Comment by mattias-symphony** [comment]
> @mattias-symphony Please describe the solution in the description. It'll help in the future if someone looks at the code to understand what clamping does exactly.

what more description could you possibly want for a small thing like this? The problem is in the ticket, the commit message tells what was done. How would you have described it without being redundant?

**Comment by VishwasShashidhar** [comment]
> what more description could you possibly want for a small thing like this? The problem is in the ticket, the commit message tells what was done. How would you have described it without being redundant?

Adding a code comment where you are writing the logic helps someone else understand what you are doing there. For example, you are taking the minimum of dispID and displays.length below

`Math.min(dispId, displays.length - 1);`

Why are we taking this approach?

And, you'll need to fill in the PR description appropriately as per the process. I understand the JIRA ticket describes the details, but, this is an open source project and some people don't have access to JIRA, and, that is the reason we have this template.

**Comment by johankwarnmarksymphony** [comment]
CLA stage is not working

**Pull request merged**
