### PR TITLE
Show SFE version in about-window

### PR DESCRIPTION
**Pull request by johankwarnmarksymphony**
## Description
A few sentences describing the overall goals of the pull request's commits. 
Describe the problem or feature in addition to a link to the 
[JIRA-ticket](https://perzoinc.atlassian.net/browse/JIRA-ticket)

## Solution Approach
Describe the approach you've taken to implement this change / resolve the issue

## Related PRs
List related PRs against other branches/repositories:

branch | PR
------ | ------
other_pr_dev | [link]()

### CODE REVIEW

**Comment by KiranNiranjan** [comment]
@johankwarnmarksymphony can you please include JIRA ticket number in every `pull request`/`commit message` else it will be harder to track

**Comment by KiranNiranjan** [comment]
Apart from the above, it LGTM 👍

**Comment by johankwarnmarksymphony** [comment]
> Apart from the above, it LGTM 👍

**Comment by johankwarnmarksymphony** [comment]
> can you please include JIRA ticket number in every `pull request`/`commit message` else it will be ha

@KiranNiranjan No jira ticket exists ;)

**Pull request merged**
