### PR TITLE
feat: I18N-978: Add configuration file for Crowdin CLI

### PR DESCRIPTION
**Pull request by infotexture**
## Description

[Crowdin](https://crowdin.com) is a cloud-based localization platform used to manage multilingual content. 

We will use Crowdin to manage the text that appears in the user interface of Symphony client apps. 

Epic [I18N-968](https://perzoinc.atlassian.net/browse/I18N-968) tracks tasks required to integrate the platform with our clients. (For details, see [Crowdin Sync Process](https://docs.google.com/document/d/1kp_j-l6psNEYcRZ0HmFC57y1yeZ0kMi3pA7kLcMg4AE).)

## Required changes

This PR adds a configuration file that describes which resources to manage: the files to be uploaded into Crowdin and the locations of the corresponding translations.

For details, see https://support.crowdin.com/cli-tool/.

✅ Tested with Crowdin CLI, source strings & translations are successfully uploaded.

## JIRA ticket

- Fixes [I18N-978](https://perzoinc.atlassian.net/browse/I18N-978)

## Related PRs

- [x] https://github.com/SymphonyOSF/SFE-Client-App/pull/17198
- [x] https://github.com/SymphonyOSF/SFE-Lite/pull/3226
- [x] https://github.com/SymphonyOSF/SIOS-Client-App/pull/4946
- [x] https://github.com/SymphonyOSF/SAndroid-Client-App/pull/3205 
- [ ] https://github.com/SymphonyOSF/SBE/pull/20877
- [x] https://github.com/SymphonyOSF/SFE-Login/pull/660
- [x] https://github.com/SymphonyOSF/SFE-RTC/pull/2335

notes: Add configuration file for Crowdin CLI

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your pull request and welcome to our community! We require contributors to sign a [Contributor License Agreement](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Legal+Requirements#LegalRequirements-ContributorLicenseAgreement) and we don't seem to have CLAs on file for these contributors to the Pull Request: (@infotexture). In order for your PR to be reviewed and merged, please follow the directions at the link above.

Project team: please **do not merge this Pull Request** until Foundation staff have confirmed that a CLA is in place for the new contributor(s) listed above.

If you still have any questions or just don't know what to do next, please email [help@finos.org](mailto:help@finos.org). /CC @finos-admin

**Comment by VishwasShashidhar** [comment]
@infotexture We'll need to wait until you are added under the CLA, we can only merge this PR post that.

@maoo Can you please do the needful?

**Review by VishwasShashidhar — APPROVED** [review]

**Review by KiranNiranjan — APPROVED** [review]

**Review by keerthi16 — APPROVED** [review]

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Pull request merged**
