### PR TITLE
electron-69: fixes the issue raised in the ticket for windows

### PR DESCRIPTION
**Pull request by VishwasShashidhar**
@lneir Please review and merge.

I have not been able to test this because I don't have the proper certificates in place.

Can you please checkout this pull request and test it on the build server and let me know if you face any issues?

And, the version of aip I have in my system is higher than what was in the repo.

### CODE REVIEW

**Comment by lneir** [comment]
you can test locally by disabling the signing.

**Comment by VishwasShashidhar** [comment]
Done, tested locally, it is working as expected.

**Comment by lneir** [comment]
looks like you used a much newer version of advanced installer and caused a bunch of other updates.  we should use the same version to do updates.  i can get you a copy of the old version and you should use that.

**Comment by VishwasShashidhar** [comment]
sure, I'll look into that.

**Comment by VishwasShashidhar** [comment]
closing this to create another PR with the older version of advanced installer.

**Pull request closed without merging**
