### PR TITLE
Electron-19 (Frameless Window)

### PR DESCRIPTION
**Pull request by KiranNiranjan**
Added Frameless Window support

### CODE REVIEW

**Comment by KiranNiranjan** [comment]
@lneir Please review. Thanks

**Comment by VishwasShashidhar** [comment]
@KiranNiranjan You need to merge master to this branch and push a new update. There are conflicts.

**Comment by KiranNiranjan** [comment]
@VishwasShashidhar I'm waiting for the design team suggestion on this and also need to make some more changes on the client app.

**Comment by KiranNiranjan** [comment]
Closing this as it is not currently required.

**Pull request closed without merging**
